name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Build project
        # Добавили CI=false, чтобы сборка не падала из-за мелких предупреждений в коде
        run: npm run build
        env:
          CI: false
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
