name: Print Pull Request Context
on:
  pull_request:
    branches: ["master"]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
#тест
