name: Print Pull Request Context
on:
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
